name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Linter
        run: |
          pip install pylint
          pylint *.py

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulate Build Step
        run: echo "Build completed successfully."

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID4 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY4 }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://aws-flying-bird-animated --delete
