name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  check:
    name: HTML/CSS Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Linters
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {}
          }' > .stylelintrc.json

      - name: Lint HTML
        run: htmlhint index.html

      - name: Lint CSS (Auto Fix)
        run: stylelint "css/*.css" --fix

  build:
    name: Build Step
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Simulate Build
        run: echo "Build completed."

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID4 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY4 }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync . s3://aws-flying-bird-animated --delete
